version: "3.7"

x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "10m"


networks:
  web:
    attachable: true

services:
  web:
    <<: *logging
    image: "ouestcode-web:20230328185322"
    build: .
    restart: unless-stopped
    ports:
      - "30000:80"
    networks:
      - web
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 3s
        order: start-first
      restart_policy:
        condition: on-failure
