version: "3.2"

networks:
  web:
    attachable: true

services:
  web:
    image: "ouestcode-web:${TAG}"
    build: .
    restart: unless-stopped
    ports:
      - "30000:80"
    networks:
      - web
