version: "3"

networks:
  web:
    external: true

services:
  web:
    build: ./app
    restart: unless-stopped
    labels:
      - traefik.backend=ouestcode
      - traefik.frontend.rule=Host:ouestcode.com
      - traefik.docker.network=web
      - traefik.port=80
      - traefik.enable=true
    networks:
      - web
