      </div>
    </div>
    <div class="container">
      <div class="footer">
	<hr/>
	<p>
	  <a href="mailto:contact@ouestcode.com">contact@ouestcode.com</a>
	  -
          <a href="tel:+33633858332">+33 (0)6 33 85 83 32</a>
	  <br>
          OuestCode, Cyril Rohr EIRL, Thorigné-Fouillard, France
	</p>
      </div>
    </div>
    <script src="https://cdn.usefathom.com/script.js" data-site="ZCOSYLGT" defer></script>
  </body>
</html>
