<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Codelicacy</title>
    <link rel="stylesheet" href="/css/style.css">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#2d363a">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#2d363a">
  </head>
  <body>
    <div class="container">
      <div class="header">
        <div class="brand">
          <a href="/"><img src="/img/codelicacy.svg" class="logo"/></a>
        </div>
        <div class="menu">
          <a href="/products" class="products">Products</a>
	  <a href="/consulting" class="consulting">Consulting</a>
	  <a href="/journal" class="journal">Journal</a>
	  <a href="/about" class="about">About</a>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="content">

