<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Codelicacy</title>
    <link rel="stylesheet" href="/css/style.css">
  </head>
  <body>
    <div class="container">
      <div class="header">
        <div class="brand">
          <a href="/"><img src="/img/codelicacy.svg" class="logo"/></a>
        </div>
        <div class="menu">
          <a href="/products" class="products">Products</a>
	  <a href="/consulting" class="consulting">Consulting</a>
	  <a href="/journal" class="journal">Journal</a>
	  <a href="/about" class="about">About</a>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="content">

