<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>OuestCode</title>
    <link rel="stylesheet" href="/style.css">
  </head>
  <body>
    <div class="container">
      <div class="header">
        <div class="brand">
          <a href="/"><img src="/img/ouestcode.svg" height=40 class="logo"/></a>
        </div>
        <div class="menu">
          <a href="/#products">Products</a>
	  <a href="/#consulting">Consulting</a>
	  <a href="/about">About</a>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="content">

