      </div>
    </div>
    <div class="container">
      <div class="footer">
	<hr/>
	<p>
	  <a href="mailto:contact@ouestcode.com">contact@ouestcode.com</a>
	  -
          <a href="tel:+33633858332">+33 (0)6 33 85 83 32</a>
	  <br>
          OuestCode, Cyril Rohr EIRL
	</p>
      </div>
    </div>
    <script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-13023229-1']);
    _gaq.push(['_setDomainName', 'crohr.me']);
    _gaq.push(['_trackPageview']);
    setTimeout("_gaq.push(['_trackEvent', '20_seconds', 'read'])", 15000);
    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
    </script>
  </body>
</html>
